name: Build installer
on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  DRIVER_VERSION: 1.2.0

permissions:
  id-token: write
  contents: read

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest
    env:
      CMAKE_GENERATOR: Visual Studio 18 2026
      WIX_DIR: "C:/Program Files (x86)/WiX Toolset v3.14/bin"
      CMAKE_POLICY_VERSION_MINIMUM: "3.5"
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Configure build environment/dependencies
      - name: Install MySQL client libs
        run: |
          curl -L https://dev.mysql.com/get/Downloads/MySQL-8.3/mysql-${{ vars.MYSQL_VERSION }}-winx64.zip -o mysql.zip
          unzip -d C:/ mysql.zip
      
      - name: Cache OpenSSL 3
        id: cache-openssl
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: C:/openssl-3
          key: ${{ runner.os }}-openssl-3.5.8

      - name: Download OpenSSL 3 source
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        shell: bash
        run: |
          curl -L https://github.com/openssl/openssl/releases/download/openssl-3.5.8/openssl-3.5.8.tar.gz -o openssl-3.5.8.tar.gz
          echo "a8f84a39918ec6415ce765d9b429d313ba97b8143169c172e734b9514464f5b2  openssl-3.5.8.tar.gz" | sha256sum -c
          tar xf openssl-3.5.8.tar.gz
          choco install nasm -y --no-progress

      - name: Build and install OpenSSL 3
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        shell: cmd
        working-directory: openssl-3.5.8
        run: |
          for /f "usebackq tokens=*" %%i in (`vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do call "%%i\VC\Auxiliary\Build\vcvars64.bat"
          set "PATH=%ProgramFiles%\NASM;%PATH%"
          perl Configure VC-WIN64A no-tests --release --prefix=C:\openssl-3\x64 --openssldir=C:\openssl-3\x64\ssl
          nmake /NOLOGO
          nmake /NOLOGO install_sw

      - name: Install OpenSSL 3 DLLs
        run: |
          cp -r C:/openssl-3/x64/bin/libssl-3-x64.dll C:/Windows/System32/
          cp -r C:/openssl-3/x64/bin/libcrypto-3-x64.dll C:/Windows/System32/

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

      - name: Cache AWS SDK libraries
        id: cache-dynamic-aws-sdk
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            aws_sdk
          key: ${{ runner.os }}-aws-sdk-dynamic-lib

      - name: Build and install AWS SDK C++
        working-directory: ./scripts
        if: steps.cache-dynamic-aws-sdk.outputs.cache-hit != 'true'
        run: |
          .\build_aws_sdk_win.ps1 x64 ${{ env.BUILD_TYPE}} ON "${{env.CMAKE_GENERATOR}}"

      - name: Setup nmake
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1

      - name: Run build installer script
        shell: pwsh
        run: |
          .\build_installer.ps1 x64 ${{ env.BUILD_TYPE}} "${{env.CMAKE_GENERATOR}}" C:/mysql-${{ vars.MYSQL_VERSION }}-winx64 "${{env.WIX_DIR}}" "C:/openssl-3/x64/include/"

      - name: Configure AWS credentials OIDC
        uses: aws-actions/configure-aws-credentials@ff717079ee2060e4bcee96c4779b553acc87447c # v4
        with:
          role-skip-session-tagging: true
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: mysql-win-signer

      - name: Configure AWS credentials Signer
        uses: aws-actions/configure-aws-credentials@ff717079ee2060e4bcee96c4779b553acc87447c # v4
        with:
          role-skip-session-tagging: true
          role-chaining: true
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}

      - name: Run signer script
        shell: pwsh
        working-directory: ./scripts
        run: |
          choco upgrade jq -y
          . ".\sign_installer.ps1"
          Invoke-SignInstaller ${{ github.workspace }}\wix winx64a ${{ env.DRIVER_VERSION}} ${{ secrets.AWS_UNSIGNED_BUCKET }} ${{ secrets.AWS_SIGNED_BUCKET }} ${{ secrets.AWS_S3_KEY }}aws-mysql-odbc-${{ env.DRIVER_VERSION}}-winx64a.msi
      
      - name: Upload Windows installer as artifact
        if: success()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: installers
          path: ${{ github.workspace }}/wix/*.msi
          if-no-files-found: error
