name: Release Draft
# This workflow is triggered on creating tags to any branch
on:
  push:
    tags:
      - "*.*.*"

env:
  BUILD_TYPE: Release

jobs:
  build-mac:
    name: MacOS
    runs-on: macos-latest
    env:
      CMAKE_GENERATOR: Unix Makefiles
      MYSQL_DIR: /usr/local/opt/mysql-client
      ODBC_DM_INCLUDES: /usr/local/include
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      # Configure build environment/dependencies
      - name: Install MySQL client libs & other dependencies
        run: |
          brew update
          brew unlink unixodbc
          brew install libiodbc mysql-client
      
      - name: Create build environment
        run: cmake -E make_directory ${{ github.workspace }}/build

      - name: Configure CMake
        run: cmake -S . -B build
                -G "$CMAKE_GENERATOR"
                -DCMAKE_BUILD_TYPE=$BUILD_TYPE
                -DMYSQLCLIENT_STATIC_LINKING=true
                -DODBC_INCLUDES=$ODBC_DM_INCLUDES
                -DCONNECTOR_PLATFORM=macos

      - name: Build driver
        working-directory: ${{ github.workspace }}/build
        run: |
          export LIBRARY_PATH=$LIBRARY_PATH:$(brew --prefix zstd)/lib/
          cmake --build .
          
      - name: Build installer
        working-directory: ${{ github.workspace }}/build
        if: success()
        run: cpack .

      # Get tag version for release
      - name: Set Version Env Variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Upload to Draft Release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          name: "AWS ODBC Driver for MySQL - v${{ env.RELEASE_VERSION }}"
          artifacts: ${{ github.workspace }}/build/aws-mysql-odbc-*.pkg
          token: ${{ secrets.GITHUB_TOKEN }}
